assert-rs/snapbox

src/elide.rs, src/lib.rs, src/runner.rs
This gives us whole-line elision but leaves out mid-line elision.
`TRYCMD=dump` will not preserve elisions on `*.out/`.
Part of #5
=> feat: Allow eliding content 

src/cargo.rs
We need to run `env` in the caller's context
=> fix: split out a `cargo_bin!`

src/filesystem.rs, src/lib.rs
These are a way to force a directory to be created that is empty.  We'll
create the directory but not copy the file over in sandboxes.  We will
also not verify these files.
=> feat!: Ignore `.keep` files

README.md, src/cases.rs, src/lib.rs, src/runner.rs, src/schema.rs, tests/cmd/basic.trycmd, tests/cmd/failure.toml, tests/cmd/schema.stdout, tests/cmd/schema.trycmd
This makes a `.trycmd` file look like:
```
$ ls
> -a
? success
```
with `>` being a line continuation and `?` being optional exit status.
=> Make `.trycmd` more cram like

src/filesystem.rs, src/runner.rs, src/schema.rs
The downside is this makes it so overwrite runs are considered failures,
even obscuring the real failure or making the user think it didn't work.
Fixes #23
=> fix: Overwrite support for *.trycmd files 

Cargo.toml, src/cargo.rs
Modeled after clap, I'm moving the extra output to a `debug` feature
people can enable when having problems.  We can later expand this to
cover debugging more cases, like parsing, etc.
=> fix: Reduce example failure output

src/runner.rs
If stdout doesn't match, we were considering this ok when it should be a
failure.
This probably broke in e4365dbf when we consolidated the message
formatting.
=> fix: Don't conflate spawn status with status

src/elide.rs, src/lib.rs
This will be useful for clap for eliding the `.exe` for windows.
I feel so dirty writing this by hand.  Who knows what corner cases are
lurkling :/.  I'm just concerned about keeping this "light".  We'll see
how this goes.
I'm also mixed about whether line `...` should look for a literal line
or also lines with inline `...`.  Going with the simple option for now.
Fixes #5
=> feat: Provide inline eliding of text

src/cases.rs, src/elide.rs, src/lib.rs, src/runner.rs, tests/cli_tests.rs, tests/cmd/vars.trycmd
This normalizes the character wildcard to `[..]` and adds built-in variables as well as user-defined ones.  All inspired by cargo in #39.
=> More extensible wildcard support

src/registry.rs, src/runner.rs, tests/cmd/unresolved.trycmd
This is helpful for when working with bins behind feature flags (like
examples).
=> fix: Ignore unknown bins

src/filesystem.rs, src/runner.rs
When a `.trycmd` file has multiple steps, we skip all steps after a
failure, assuming there is a dependency between them.  This is only
strictly true when the file system is being touched.  Otherwise, the
relationship is more nebulous and depends on how the person setup the
tests.
=> fix: Run all steps when no dependency

Cargo.toml
Part of https://github.com/clap-rs/clap/pull/3172
=> Bump `escargot` version to `0.5.7`

src/lib.rs, src/schema.rs
BREAKING CHANGE: `bash` and `sh` info strings for code blocks are now
ignored, switch to `console` or `trycmd`.
=> fix(md)!: Use `console` for infostring

src/schema.rs, tests/cmd/basic.trycmd, tests/cmd/multistep.trycmd, tests/cmd/stdout.trycmd, tests/cmd/unresolved.trycmd, tests/cmd/vars.trycmd
Because of how we parsed the file, the stdout for an `md` code block
always had a newline at the end.  This prevents verifying applications
that do not output a trailing newline (usually applications should).
By stripping and re-adding the newline, we also provide more visual
separarion between the commands, making the output eaiser to read.
BREAKING CHANGE: All `md` command outputs need an extra newline
=> feat(md)!: Allow verifying without trailing newline

src/elide.rs, src/filesystem.rs, src/lib.rs
Cargo does this.  I've been trying to avoid it but its inevitable
because there is the chance we hide something important.
=> feat!: Normalize path separators

Cargo.toml, src/schema.rs, tests/cmd/schema.stdout, tests/cmd/stderr_toml.toml
This doesn't work with binary data but should be convinient for text
which is the majority of cases.  This should reduce the proliferation of
files in cases like killercup/cargo-edit#566.
=> feat: Allow stdin/stdout/stderr in toml 

Cargo.toml, src/filesystem.rs, src/runner.rs, src/schema.rs
`binary` only impacts stdin/stdout/stderr.  File systems tend to be too
diverse to be controlled by a single flag.  Before we erred on the side
of always assuming text.  Now we will assume a file is text only if it
doesn't look like its binary and it is valid UTF-8
Fixes #61
=> fix: Auto-detect binary files

crates/snapbox/src/assert.rs, crates/snapbox/src/cmd.rs, crates/snapbox/src/harness.rs, crates/snapbox/src/lib.rs, crates/snapbox/src/path.rs, crates/snapbox/src/report/diff.rs, crates/snapbox/src/substitutions.rs, src/runner.rs
While `actual == expected` reads more naturally to me, we are diffing as
`diff expected actual`, so being consistent with that.
=> fix: Be consistent in parameter order

crates/snapbox/src/assert.rs
Originally, if no expected_path existed, we'd normalize `actual` as
binary data and write that out.  On the next run, we'd then detect its
text and try to normalize.
Now we assume text and normalize as much so remove the extra overwrite
step.
=> fix: Only overwrite once in majority case

crates/snapbox/src/path.rs
Originally, we could only populate a temp dir, so we knew it was
created.  Now we need to implicitly create it.
=> fix: Implicitly create dest

crates/snapbox/Cargo.toml, crates/snapbox/src/path.rs
This is inspired by cargo's tests
=> fix(path): Avoid mtime races

src/schema.rs
Our simple code-fence extractor could only handle triple-backtick code
fences which didn't allow for users to escape triple-backtick code
fences.  We now support 3+ backtick code fences so users can use
whatever code fence they want.
This is a workaround for and a step towards https://github.com/assert-rs/trycmd/issues/96 which involves
automatically adapting code fences.
=> fix(trycmd): Allow escaped code fences 

src/lib.rs
Hello,
It was not clear to me how to pass `args` to the binary when using `*.toml` format, and since it is the argument most users will use, so it makes sense to directly put it in the doc.
=> Better document `*.toml` format

crates/snapbox/src/assert.rs, crates/snapbox/src/cmd.rs, crates/snapbox/src/data.rs, crates/snapbox/src/harness.rs, crates/snapbox/src/lib.rs, src/schema.rs
This adds a `DataFormat` enum to help with adding new data formats. This allows a user to specify what data format they want not just binary or text. Suggested in [this comment](https://github.com/assert-rs/trycmd/pull/106#discussion_r920180301)
=> add `DataFormat` enum

crates/snapbox/src/assert.rs, crates/snapbox/src/data.rs, crates/snapbox/src/path.rs
This changes `try_text` into `try_coerce` to support changing of a `Data`'s underlying `DataFormat` to more than just `Text`.
This adds `try_coerce` which can be extended to allow conversion between different `DataFormat`s. This also adds `Data::format` which gives the current `DataFormat` of the underlying `Data`. This is useful for when you are trying to convert one `Data` to another `Data`'s `DataFormat` (`actual.try_coerce(expected.format())`)
=> refactor(snapbox)!: Change `try_text` to `try_coerce`

src/schema.rs
Clippy was throwing a warning about "unnecessary closure used to substitute value for `Option::None`". This fixes the warning by using the suggestion Clippy gave.
<details><summary>Full Warning</summary>
<p>
```
warning: unnecessary closure used to substitute value for `Option::None`
--> src/schema.rs:178:32
|
178 |                   let tick_end = line
|  ________________________________^
179 | |                     .char_indices()
180 | |                     .find_map(|(i, c)| (c != '`').then(|| i))
181 | |                     .unwrap_or_else(|| line.len());
| |______________________----------------------------^
|                        |
|                        help: use `unwrap_or(..)` instead: `unwrap_or(line.len())`
|
= note: `#[warn(clippy::unnecessary_lazy_evaluations)]` on by …
```
=> fix clippy warning

crates/snapbox/src/report/diff.rs
For now, this isn't configurable.  The defaults favor showing as much
context as possible.
=> feat(diff): Elide long sections of unchanged output

crates/snapbox/CHANGELOG.md, crates/snapbox/src/assert.rs
=> fix(snap): Don't normalize paths for equality

crates/snapbox/src/assert.rs, crates/snapbox/src/data.rs, crates/snapbox/src/harness.rs, crates/snapbox/src/lib.rs, crates/snapbox/src/path.rs, crates/snapbox/src/report/diff.rs, src/runner.rs, src/schema.rs
This is a part of #92.
This PR is to help move forward the effort with supporting structured data formats. Part of this effort showed that there needed to be a better way to specify what normalization operation was wanted and later to unify what the operations are doing. 
- Abstract lower level `map_text` calls as `normalize` with operation types
- By providing build blocks before, we were hoping to allow people to plug in their own normalization routines.  However, when we add structured data support, it will need to operate on internal data initially as we work out details, so we're making all of the normalization logic private, just allowing the caller to which built-in normalization can be done.
- change `as_str` to `try_string` and update its return to be `Option<String>`
- The …
=> refactor(snapbox): Changes to normalization

crates/snapbox/src/data.rs, src/runner.rs
@epage [noticed](https://github.com/assert-rs/trycmd/pull/106#discussion_r951809165) that `into_text` was only being used in `make_text` and `make_text` were only being used in one place and both could be removed by switching the single caller of `make_text` to use `try_coerce` 
This removes `into_string` and  `make_text`, and updates the one caller of `make_text` to use `try_coerce` instead
=> refactor(snapbox): Remove `into_string`

crates/snapbox/src/harness.rs
This will now report back to the user if `SNAPSHOTS=ignore` is used
=> fix: Re-add ignore reporting

Cargo.lock, crates/snapbox/Cargo.toml, crates/snapbox/src/data.rs
I wanted to make sure I was on the right track when adding json support for `snapbox`. I am a bit worried about `Data::deserialize` and how ergonomic it is to add a new format. This also only looks at the file type and has no other way to set the `Data` variant to `Json`. This currently does not add support for json specific matching. When added I will probably use something similar to [cargo's json matching](https://github.com/rust-lang/cargo/blob/9c4bae65b743df07d10a58836a5ee09103050d02/crates/cargo-test-support/src/compare.rs#L525). There shouldn't be any breaking changes but I could be wrong and might have missed something. 
This is a part of #92
=> json support for `snapbox`

schema.json, src/registry.rs, src/runner.rs, src/schema.rs, tests/cli_tests.rs, tests/cmd/ignored_bin.trycmd, tests/cmd/unresolved.trycmd
This was originally written this way to be a low effort way to ignore,
especially if you wanted a markdown block of code that interspersed
different commands.
This cane make it harder to root cause failures.  In the mean time, you can
- Mark the whole code fence as ignored
- Mark the status of the program as skipped
- Mark the binary as ignored (new)
Fixes #105
=> Errorfix(trycmd): Error, instead of ignore, unknown bins

src/runner.rs, tests/cmd/unresolved.trycmd
This reverts commit bd6922457c7b37b2a62b42a10de51f74dc96be21.
When working on this, we forgot the case of conditionally existing examples.
#105 was re-opened.  As this turns an error into a working case, this shouldn't break compatibility.
=> Revert "fix(trycmd): Error, instead of ignore, unknown bins"

src/spec.rs
Turns out trycmd is still broken because of https://github.com/rayon-rs/rayon/issues/952, but that will presumably get fixed eventually.
Closes #152
=> Ignore every test under miri

src/runner.rs
=> fix: don't fail with overwrite

src/runner.rs
closes #193
I don't think the clone here is avoidable without unsafe or changing `Result<Output, Output>` to `(bool, Output)`
=> fix: Only exit peacefully when all failures are overwritten

Cargo.lock, Cargo.toml, crates/snapbox/Cargo.toml, crates/snapbox/examples/example-fixture.rs, crates/snapbox/src/cmd.rs, src/cargo.rs
I was pulling `trycmd` into a project just for compiling examples in an easier way.
=> feat(snap): Allow compiling examples

crates/snapbox/Cargo.toml
This prevents build of useless deps -> faster build
=> snapbox: cfg out platform dependent deps

crates/snapbox-macros/LICENSE-APACHE, crates/snapbox-macros/LICENSE-MIT, crates/snapbox/LICENSE-APACHE, crates/snapbox/LICENSE-MIT
The MIT and Apache-2.0 licenses require that redistributed sources
contain a copy of the license text.
=> link LICENSE files into snapbox and snapbox-macros crates

crates/snapbox/src/data.rs
This adds support for `"{...}"` in a structured data array to capture multiple elements. 
It adds support for wildcards by splitting the expected output over wildcards; this creates groups for us to process the actual output with. Between these groups, we transform everything into a single wildcard.
closes #133
=> feat(snapbox): Add wildcard for structured data

crates/snapbox/Cargo.toml, crates/snapbox/examples/diff.rs, crates/snapbox/src/report/color.rs
=> fix(snap): Finish swapping colors 

crates/snapbox/src/assert.rs, crates/snapbox/src/data/mod.rs, crates/snapbox/src/data/runtime.rs, crates/snapbox/src/data/source.rs, crates/snapbox/src/data/tests.rs, crates/snapbox/src/lib.rs, crates/snapbox/src/macros.rs, crates/snapbox/src/path.rs, crates/snapbox/tests/assert.rs
=> feat(snap): Allow inline snapshotting

crates/snapbox/src/substitutions.rs, src/cases.rs
Solved the overwrite problem by allowing to remove previous entries
This is the snapbox side of #153
=> fix(snap): Allow multiple values map to a variable

Cargo.lock, crates/snapbox/Cargo.toml, crates/snapbox/src/data/format.rs, crates/snapbox/src/data/mod.rs, crates/snapbox/src/data/normalize.rs
=> feat: `term-svg` for snapshotting of terminal styling

crates/snapbox/src/assert.rs, crates/snapbox/src/path.rs
It's probably better to reuse `Assert::normalize_match`, but that requires more API changing. This was just the quickest way for me to get my tests passing 😁
=> fix: Respect Assert::normalize_paths when running subset_matches

crates/snapbox/src/data/mod.rs, crates/snapbox/src/data/runtime.rs, crates/snapbox/src/macros.rs
Before our auto-named snapshots used line numbers to make them unique.
This would fail within macros.
They could easily change for no good reason, requiring deleting the
entire snapshot directory and restarting.
In short, we change
- from `src/<mod>/snapshots/<file>-<line>.txt`
- to `tests/snapshots/<normalized_fn_path>.txt` where `<normalized_fn_path> = <fn_path>.replace("::", "__")`
Our paths were relative to the test file.
I reconsidered this when doing the above because the function name made
things less unique.
In making them unique, I'd need to extend the path a lot
(`src/<path>/snapshots/<path>.txt`).
So I moved them to the root to all be together.
Not considering this a breaking change because of how non-deterministic the file names were before.
=> fix(snap): Provide more stable snapshots 

crates/snapbox/src/data/mod.rs, crates/snapbox/src/data/runtime.rs, crates/snapbox/src/data/source.rs, crates/snapbox/tests/assert.rs
Rather than dealing with the special cases where this doesn't exist, let's just not do this.
This also aligns with the general style within Cargo's tests.
Fixes #267
=> fix(snap)!: Remove inline snapshot indent support

crates/snapbox/src/data/runtime.rs, crates/snapbox/src/data/source.rs, crates/snapbox/tests/assert.rs
In using snapshots, I found the leading newline so good that I feel like we should have a trailing newline as well!
=> fix(snap)!: Include a trailing newline in snapshots

crates/snapbox/src/harness.rs, crates/snapbox/src/lib.rs
BREAKING CHANGE: `Case` requires a `format: Option<DataFormat>` field
Fixes #263
=> feat(snap)!: Allow Harness users to specify DataFormat

crates/snapbox/src/data/format.rs, crates/snapbox/src/data/mod.rs, crates/snapbox/src/data/normalize.rs
Looks like ndjson was merged into jsonlines, so went with that.
One difference at one point was allowing blank lines from what I've
heard.  I'm not seeing it mentioned in jsonlines but went with
supporting it.
Part of #92
=> feat(snap): Jsonlines support 

crates/snapbox/src/substitutions.rs
There isn't a succinct way to describe this set of changes.
Know changes:
- You can now end a `...` with a line containing `[..]`
- Variables are always substituted, rather than only when used in the
pattern
- We don't try as hard to recover from diverging input/pattern
=> fix(snap): Change how we normalize matches 

crates/snapbox/src/harness.rs, crates/snapbox/src/lib.rs
Generalize the API to allow more flexibility in the future
=> fix(harness)!: Future proof the API

crates/snapbox/src/data/mod.rs, crates/snapbox/src/data/runtime.rs, crates/snapbox/src/lib.rs, crates/snapbox/src/macros.rs, crates/snapbox/tests/assert.rs
This leaves us room to evaluate #223
Fixes #226
=> feat(assert): Add assert_data_eq! 

crates/snapbox/src/data/mod.rs, crates/snapbox/src/dir/dir.rs, crates/snapbox/src/dir/mod.rs, crates/snapbox/src/dir/ops.rs, crates/snapbox/src/dir/root.rs, crates/snapbox/src/lib.rs
BREAKING CHANGE: Remove `copy_template` and `Walk`
=> feat(dir)!: Add Dir trait with in-memory and filesystem impls

crates/snapbox/src/assert/error.rs, crates/snapbox/src/assert/mod.rs, crates/snapbox/src/cmd.rs, crates/snapbox/src/harness.rs
=> refactor(harness): Reuse more Assert logic

crates/snapbox/src/filter/redactions.rs
Cherry pick a1995e573b5a94b35c6bbde80f32fd6ffafff829 (#279)
=> refactor(snap): Simplify the applying of substitutions

crates/snapbox/src/assert/mod.rs, crates/snapbox/src/cmd.rs, crates/snapbox/src/data/mod.rs, crates/snapbox/src/data/runtime.rs, crates/snapbox/src/data/source.rs, crates/snapbox/src/lib.rs, crates/trycmd/src/runner.rs
This has everything from #292 except the removal of `Into<Data>` which is a breaking change meant to make it easier to discover what types `IntoData` can be used on.
=> feat(data): Add IntoData for easier initialization 

Cargo.lock, crates/snapbox/Cargo.toml, crates/snapbox/src/data/mod.rs, crates/snapbox/src/lib.rs
Cherry pick f0aece981c01573b0a2d415c3e30570b4d52ce66 (#293)
=> feat(data): Add IntoJson

crates/snapbox/CHANGELOG.md, crates/snapbox/src/assert/mod.rs, crates/snapbox/src/data/normalize.rs, crates/snapbox/src/dir/diff.rs, crates/snapbox/src/filter/mod.rs, crates/snapbox/src/filter/test.rs, crates/trycmd/src/runner.rs, crates/trycmd/src/schema.rs
`FilterPaths` as a concept doesn't make sense.  What the filter is doing
is normalizing paths.
ditto for newlines
=> fix(filter): Revert filter renames 

.github/workflows/ci.yml, crates/snapbox/Cargo.toml, crates/trycmd/Cargo.toml, crates/tryfn/Cargo.toml
The CI job I added in this PR is something I try to run on all my crates as well. It's something that catch if the crate (or a transitive dependency) has under-specified a dependency.
`cargo +nightly update -Z minimal-versions` downgrades the entire dependency tree to the lowest allowed versions according to all the dependency semver specs in their `Cargo.toml` files.
It's very common to just add `foo = "0.3"` manually and then write code and run. Not realizing cargo automatically pulls in the latest version at the time. That might be `foo 0.3.8` and you might unknowingly depend on features introduced in `foo 0.3.4`. A CI check like this makes sure you don't under-specify version requirements like that.
I found this because I depend on `trycmd` and this became an error with `filetime`. …
=> Fix minimal versions dependencies

crates/snapbox/src/assert/mod.rs, crates/snapbox/src/data/runtime.rs
=> fix(inline): Fail update on conflict

crates/snapbox/src/assert/mod.rs, crates/snapbox/src/data/filters.rs, crates/snapbox/src/data/mod.rs, crates/snapbox/tests/testsuite/assert.rs
=> feat(assert): Allow comparing json to jsonlines 

crates/snapbox/src/filter/pattern.rs
Verified this against cargo in rewriting some tests
Fixes #352
=> fix(filter): Take redactions into account for Array elides

crates/trycmd/Cargo.toml
=> fix(trycmd): Ensure colors are stripped with TERM=dumb

crates/snapbox/src/filter/pattern.rs
We fixed this for the ordered case in #358 but missed the unordered
case.
=> fix(filter): When checking unordered arrays, check normalized values 

Cargo.lock
Snapbox is currently unbuildable on AIX target due to problems with the versions of dependencies `libc`, `os_pipe` and `wait-timeout` missing essential fixes need to build. This PR moves these dependencies to sufficient new versions to resolve these build issues.
=> Move up libc/os_pipe/wait-timeout deps
