assert-rs/snapbox

- Cargo.toml
- src/diff.rs
- src/elide.rs
- src/lib.rs
- src/lines.rs
- src/runner.rs
> feat: Diff output

- src/runner.rs
Documentation helps for thise who initially wrote tests but we need to
help the developers who might not be familiar with trycmd.
> fix: Help users interact

- src/runner.rs
- src/schema.rs
- tests/cli_tests.rs
- tests/cmd/multistep.out/file.txt
- tests/cmd/multistep.trycmd
This allows sequencing commands or just testing multiple case in a
single file.
> feat: Multi-step `.trycmd` files

- src/runner.rs
Because of #23, `TRYCMD=overwrite` will dump meaningless files for
`*.trycmd` files which people are likely to add and assume work.
For now, we are relying on the file being overwritten existing or not to
help detect when we should allow overwrite.
> fix: Don't leave unused files on overwrite

- src/elide.rs
> Fix substitutions

- src/elide.rs
- src/filesystem.rs
- src/registry.rs
- src/runner.rs
Both in cobalt and cargo-edit, found several problems with how we deal with our variables.
> Improve substitution handling

- Cargo.toml
- crates/fs_snapshot/CHANGELOG.md
- crates/fs_snapshot/Cargo.toml
- crates/fs_snapshot/README.md
- crates/fs_snapshot/src/color.rs
- crates/fs_snapshot/src/diff.rs
- crates/fs_snapshot/src/harness.rs
- crates/fs_snapshot/src/lib.rs
- crates/fs_snapshot/src/lines.rs
The hope is to share more logic between the two to the point that people can "create" their own trycmd from fs_snapshot.
> chore: Pull in fs_snapshot

- crates/snapbox/src/cmd.rs
- crates/snapbox/src/lib.rs
- crates/snapbox/src/path.rs
Based on my experience porting cargo-edit over
> Polish snapbox

- src/lib.rs
> docs: Note examples

- src/lib.rs
> docs(trycmd): Clarify behavior of fs.sandbox

- crates/snapbox/CHANGELOG.md
- crates/snapbox/src/assert.rs
- crates/snapbox/src/utils/mod.rs
This handles the snapbox side of #91.  We'll need to update the plumbing
in trycmd to get this to all the right places.  For now this also lets
us experiment with it where we can more easily change the API.
> feat(assert): Allow disabling path normalization

- Cargo.lock
- crates/snapbox/Cargo.toml
- crates/snapbox/src/cmd.rs
- src/bin/bin-fixture.rs
- src/runner.rs
> feat: Report signal

- src/schema.rs
> fix(trycmd): Allow empty code fences

- src/lib.rs
- src/runner.rs
- src/schema.rs
> fix: overwrite command status with TRYCMD=overwrite

- crates/snapbox/src/report/diff.rs
Been thinking on this further and aligning with the common case is probably more important than the possibility of what is or isn't "right".
Fixes #228
> fix(snap): Swap diff colors

- src/schema.rs
This is a partial revert of db1dcb0.
More examination will be needed to get that to work.
Fixes #269
> fix(trycmd): Ensure overwrite happens

- crates/snapbox/src/substitutions.rs
This fixes a regression from #279
> fix(sub): Ensure variables are put in data

- crates/snapbox/src/data/mod.rs
- crates/snapbox/src/data/normalize.rs
- crates/snapbox/src/data/tests.rs
- crates/snapbox/src/report/diff.rs
> refactor(snapbox): Recreate previous refactors

- crates/snapbox/src/data/format.rs
- crates/snapbox/src/data/mod.rs
- crates/snapbox/src/data/normalize.rs
- crates/snapbox/src/data/source.rs
Cherry pick 62ddc26979e9839d247bf25b9dac83ad1dfd181b (#290)
> docs(data): Clarify how to use the API

- crates/snapbox/src/filter/redactions.rs
> refactor(filter): Prepare for changing eliding

- crates/snapbox/src/lib.rs
Cherry pick 41bfb95e432ca6b105ebcccb461c8533a279f28b (#294)
> docs: Hide debug macro

- crates/snapbox/src/data/mod.rs
Cherry pick 49830509eb3cde65a5dd0d0566baf887472a0d2d (#293)
> docs(data): Call out ToString

- crates/snapbox/src/filter/mod.rs
- crates/snapbox/src/filter/redactions.rs
- crates/snapbox/src/lib.rs
This will give us more implementation flexibility
Cherry pick 286ac5d (assert-rs#281)
Cherry pick be4ad91 (assert-rs#284)
Cherry pick 9e4ad59 (assert-rs#285)
> fix(sub)!: Abstract away substitution values

- Cargo.lock
- crates/snapbox/src/assert/mod.rs
- crates/snapbox/src/harness.rs
- crates/tryfn/CHANGELOG.md
- crates/tryfn/Cargo.toml
- crates/tryfn/LICENSE-APACHE
- crates/tryfn/LICENSE-MIT
- crates/tryfn/README.md
- crates/tryfn/src/lib.rs
Cherry pick 8e26ddb9cd402d8b0786cf3934fbd9cf6718df16 (#295) Cherry pick c736e0317518cb078d96b4a82b3b72293c077566 (#295)
> fix(tryfn): Split out harness

- crates/snapbox/src/assert/mod.rs
This can be used for very custom hacks
> fix(assert): Allow access to Redactions

- crates/trycmd/src/lib.rs
> docs(trycmd): Update broken links
